import * as Index from './index';
export { Camera } from "./engine/Camera";
export { Graphics2D } from "./engine/Graphics2D";
export { Main } from "./engine/Main";
export { Character } from "./game/Character";
export { Component } from "./game/Component";
export { IEntity as Entity } from "./game/Entity";
export { Particle } from "./game/Particle";
export { ParticleCluster, ClusterConnectionStyle } from "./game/ParticleCluster";
export { Player } from "./game/Player";
export { Scene } from "./game/Scene";
export { BarGraph } from "./game/ui/BarGraph";
export { Button } from "./game/ui/Button";
export { Graph } from "./game/ui/Graph";
export { Composite } from "./game/ui/Composite";
export { InputField } from "./game/ui/InputField";
export { Label } from "./game/ui/Label";
export { Layout, LayoutDirection, LayoutFloat, LayoutConstraint, LayoutAlignment } from "./game/ui/Layout";
export { LayoutManager } from "./game/ui/LayoutManager";
export { Panel } from "./game/ui/Panel";
export { RasterPanel } from "./game/ui/RasterPanel";
export { Scale } from "./game/ui/Scale";
export { TextArea } from "./game/ui/TextArea";
export { TextModule, TextAlignment, Font } from "./game/ui/TextModule";
export { TextModuleHandler } from "./game/ui/TextModuleHandler";
export { Texture } from "./game/ui/Texture";
export { IntersectTypes } from "./maths/IntersectTypes";
export { Matrix3 } from "./maths/Matrix3";
export { PerlinNoise } from "./maths/PerlinNoise";
export { Point } from "./maths/Point";
export { Random } from "./maths/Random";
export { Rectangle } from "./maths/Rectangle";
export { Segment } from "./maths/Segment";
export { SegmentIntersectionEvent } from "./maths/SegmentIntersectionEvent";
export { SimplexNoise, NoiseInputs } from "./maths/SimplexNoise";
export { Vector2 } from "./maths/Vector2";
export { Vector3 } from "./maths/Vector3";
export { CollisionBounds } from "./physics/CollisionBounds";
export { CollisionEvent } from "./physics/CollisionEvent";
export { CollisionHandler } from "./physics/CollisionHandler";
export { CollisionType } from "./physics/CollisionType";
export { Ray } from "./physics/Ray";
export { RayCastResult } from "./physics/RayCastResult";
export { RayPlacement } from "./physics/RayPlacement";
export { Clipboard } from "./util/Clipboard";
export { Color } from "./util/Color";
export { CssUtils } from "./util/CssUtils";
export { Handler } from "./util/Handler";
export { Input } from "./util/Input";
export { KeyHandler } from "./util/KeyHandler";
export { MouseHandler, MouseButton, Cursor } from "./util/MouseHandler";
export { MouseMoveEvent } from "./util/MouseMoveEvent";
export { MultiKeyEvent } from "./util/MultiKeyEvent";
export { MultiMouseEvent } from "./util/MultiMouseEvent";
export { Utils } from "./util/Utils";
export { BrowserWarning } from "./BrowserWarning";
export { DebugUi } from "./DebugUi";
export declare class Strum2dIndex {
    Camera: typeof Index.Camera;
    Graphics2D: typeof Index.Graphics2D;
    Main: typeof Index.Main;
    Character: typeof Index.Character;
    Component: typeof Index.Component;
    Entity: typeof Index.Entity;
    Particle: typeof Index.Particle;
    ParticleCluster: typeof Index.ParticleCluster;
    ClusterConnectionStyle: typeof Index.ClusterConnectionStyle;
    Player: typeof Index.Player;
    Scene: typeof Index.Scene;
    BarGraph: typeof Index.BarGraph;
    Button: typeof Index.Button;
    Graph: typeof Index.Graph;
    Composite: typeof Index.Composite;
    InputField: typeof Index.InputField;
    Label: typeof Index.Label;
    Layout: typeof Index.Layout;
    LayoutDirection: typeof Index.LayoutDirection;
    LayoutFloat: typeof Index.LayoutFloat;
    LayoutConstraint: typeof Index.LayoutConstraint;
    LayoutAlignment: typeof Index.LayoutAlignment;
    LayoutManager: typeof Index.LayoutManager;
    Panel: typeof Index.Panel;
    RasterPanel: typeof Index.RasterPanel;
    Scale: typeof Index.Scale;
    TextArea: typeof Index.TextArea;
    TextModule: typeof Index.TextModule;
    TextAlignment: typeof Index.TextAlignment;
    Font: typeof Index.Font;
    TextModuleHandler: typeof Index.TextModuleHandler;
    Texture: typeof Index.Texture;
    IntersectTypes: typeof Index.IntersectTypes;
    Matrix3: typeof Index.Matrix3;
    PerlinNoise: typeof Index.PerlinNoise;
    Point: typeof Index.Point;
    Random: typeof Index.Random;
    Rectangle: typeof Index.Rectangle;
    Segment: typeof Index.Segment;
    SegmentIntersectionEvent: typeof Index.SegmentIntersectionEvent;
    SimplexNoise: typeof Index.SimplexNoise;
    Vector2: typeof Index.Vector2;
    Vector3: typeof Index.Vector3;
    CollisionBounds: typeof Index.CollisionBounds;
    CollisionEvent: typeof Index.CollisionEvent;
    CollisionHandler: typeof Index.CollisionHandler;
    CollisionType: typeof Index.CollisionType;
    Ray: typeof Index.Ray;
    RayCastResult: typeof Index.RayCastResult;
    RayPlacement: typeof Index.RayPlacement;
    Clipboard: typeof Index.Clipboard;
    Color: typeof Index.Color;
    CssUtils: typeof Index.CssUtils;
    Handler: typeof Index.Handler;
    Input: typeof Index.Input;
    KeyHandler: typeof Index.KeyHandler;
    MouseHandler: typeof Index.MouseHandler;
    MouseButton: typeof Index.MouseButton;
    Cursor: typeof Index.Cursor;
    MouseMoveEvent: typeof Index.MouseMoveEvent;
    MultiKeyEvent: typeof Index.MultiKeyEvent;
    MultiMouseEvent: typeof Index.MultiMouseEvent;
    Utils: typeof Index.Utils;
    BrowserWarning: typeof Index.BrowserWarning;
    DebugUi: typeof Index.DebugUi;
}
declare global {
    interface Window {
        main: Index.Main;
        camera: Index.Camera;
        Main: {};
        Utils: {};
        Strum2d: Strum2dIndex;
        _root: string;
    }
    const Strum2d: Strum2dIndex;
    const _root: string;
}
